version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=0xVqaK$$4JUqG
  migration:
    image: alexlowe64/red-backend-migration:latest
    depends_on:
      - "mssql"
  api:
    image: alexlowe64/red-backend:latest
    depends_on:
      - "migration"
    ports:
      - 10001:80
  frontend:
    image: alexlowe64/red-frontend:latest
    depends_on:
      - "api"
    ports:
      - 10002:80
volumes:
  mssql-data:
